import jsPDF from 'jspdf';
import { FullAuditResults } from '../types';

export function generatePDF(results: FullAuditResults, whiteLabel?: { companyName: string; primaryColor?: string }): jsPDF {
  const doc = new jsPDF();
  const primaryColor = whiteLabel?.primaryColor || '#91CB5A';
  const companyName = whiteLabel?.companyName || 'ScaleFront.io';

  // Helper functions
  const addHeader = (text: string, y: number) => {
    doc.setFontSize(16);
    doc.setTextColor(primaryColor);
    doc.text(text, 20, y);
    doc.setTextColor('#000000');
  };

  const addSubheader = (text: string, y: number) => {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(text, 20, y);
    doc.setFont('helvetica', 'normal');
  };

  const addText = (text: string, y: number, maxWidth = 170) => {
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, 20, y);
    return y + (lines.length * 5);
  };

  const getScoreColor = (score: number): string => {
    if (score >= 80) return '#10B981'; // green
    if (score >= 60) return '#F59E0B'; // yellow
    return '#EF4444'; // red
  };

  let yPos = 20;

  // Title Page
  doc.setFontSize(24);
  doc.setTextColor(primaryColor);
  doc.text('Website Audit Report', 105, yPos, { align: 'center' });

  yPos += 15;
  doc.setFontSize(14);
  doc.setTextColor('#666666');
  doc.text(`Generated by ${companyName}`, 105, yPos, { align: 'center' });

  yPos += 20;
  doc.setFontSize(12);
  doc.setTextColor('#000000');
  doc.text(`URL: ${results.url}`, 20, yPos);
  yPos += 7;
  doc.text(`Date: ${new Date(results.timestamp).toLocaleString()}`, 20, yPos);

  // Overall Score
  yPos += 20;
  doc.setFontSize(18);
  doc.setTextColor(primaryColor);
  doc.text('Overall Health Score', 20, yPos);

  yPos += 10;
  doc.setFontSize(48);
  doc.setTextColor(getScoreColor(results.overallScore));
  doc.text(results.overallScore.toString(), 90, yPos);
  doc.setFontSize(12);
  doc.text('/100', 115, yPos);

  // Category Scores
  yPos += 25;
  doc.setFontSize(16);
  doc.setTextColor(primaryColor);
  doc.text('Category Breakdown', 20, yPos);

  const categories = [
    { name: 'SEO', score: results.seo.score },
    { name: 'Performance', score: results.performance.score },
    { name: 'Accessibility', score: results.accessibility.score },
    { name: 'Security', score: results.security.score },
    { name: 'Shopify', score: results.shopify.score },
  ];

  yPos += 10;
  categories.forEach((cat) => {
    doc.setFontSize(11);
    doc.setTextColor('#000000');
    doc.text(cat.name, 25, yPos);

    // Score bar
    doc.setFillColor(getScoreColor(cat.score));
    doc.rect(70, yPos - 4, (cat.score / 100) * 80, 5, 'F');
    doc.setDrawColor('#E5E7EB');
    doc.rect(70, yPos - 4, 80, 5, 'S');

    // Score number
    doc.setTextColor(getScoreColor(cat.score));
    doc.text(cat.score.toString(), 155, yPos);

    yPos += 10;
  });

  // New page for issues
  doc.addPage();
  yPos = 20;

  addHeader('Critical & High Priority Issues', yPos);
  yPos += 10;

  const criticalIssues = [
    ...results.seo.issues,
    ...results.performance.issues,
    ...results.accessibility.issues,
    ...results.security.issues,
    ...results.shopify.issues,
  ].filter(i => i.severity === 'critical' || i.severity === 'high');

  if (criticalIssues.length === 0) {
    yPos = addText('✓ No critical or high priority issues found!', yPos);
  } else {
    criticalIssues.forEach((issue, index) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(issue.severity === 'critical' ? '#EF4444' : '#F59E0B');
      doc.text(`${index + 1}. ${issue.issue}`, 20, yPos);

      yPos += 5;
      doc.setFont('helvetica', 'normal');
      doc.setTextColor('#000000');
      yPos = addText(`Category: ${issue.category}`, yPos);
      yPos = addText(`Recommendation: ${issue.recommendation}`, yPos);
      yPos += 5;
    });
  }

  // SEO Details
  doc.addPage();
  yPos = 20;
  addHeader('SEO Analysis', yPos);
  yPos += 10;
  addSubheader(`Score: ${results.seo.score}/100`, yPos);
  yPos += 8;

  results.seo.issues.forEach((issue) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(9);
    doc.setTextColor('#666666');
    yPos = addText(`• ${issue.issue}: ${issue.recommendation}`, yPos);
    yPos += 3;
  });

  // Performance Details
  doc.addPage();
  yPos = 20;
  addHeader('Performance Analysis', yPos);
  yPos += 10;
  addSubheader(`Score: ${results.performance.score}/100`, yPos);
  yPos += 8;

  results.performance.issues.forEach((issue) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(9);
    doc.setTextColor('#666666');
    yPos = addText(`• ${issue.issue}: ${issue.recommendation}`, yPos);
    yPos += 3;
  });

  // Recommendations
  doc.addPage();
  yPos = 20;
  addHeader('Top Recommendations', yPos);
  yPos += 10;

  results.recommendations.slice(0, 10).forEach((rec, index) => {
    if (yPos > 260) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(primaryColor);
    doc.text(`${index + 1}. ${rec.title}`, 20, yPos);

    yPos += 6;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor('#000000');
    yPos = addText(rec.description, yPos);

    doc.setTextColor('#666666');
    yPos = addText(`Impact: ${rec.impact}`, yPos);
    yPos += 8;
  });

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor('#999999');
    doc.text(
      `Generated by ${companyName} | Page ${i} of ${pageCount}`,
      105,
      290,
      { align: 'center' }
    );
  }

  return doc;
}

export function downloadPDF(results: FullAuditResults, whiteLabel?: { companyName: string; primaryColor?: string }): void {
  const doc = generatePDF(results, whiteLabel);
  const url = new URL(results.url);
  const filename = `audit-report-${url.hostname}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
}
