import { FullAuditResults } from '../types';

interface EmailOptions {
  to: string;
  subject: string;
  html: string;
}

export async function sendEmail(options: EmailOptions): Promise<boolean> {
  // Using Resend API (you'll need to add RESEND_API_KEY to .env)
  const apiKey = process.env.RESEND_API_KEY;

  if (!apiKey) {
    console.log('[Email] No API key configured. Email would be sent to:', options.to);
    return false;
  }

  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: process.env.EMAIL_FROM || 'Earn Auditor <audit@scalefront.io>',
        to: options.to,
        subject: options.subject,
        html: options.html,
      }),
    });

    return response.ok;
  } catch (error) {
    console.error('[Email] Failed to send:', error);
    return false;
  }
}

export function generateAuditEmail(results: FullAuditResults, companyName = 'ScaleFront.io'): string {
  const criticalIssues = [
    ...results.seo.issues,
    ...results.performance.issues,
    ...results.accessibility.issues,
    ...results.security.issues,
    ...results.shopify.issues,
    ...results.salesOptimization.issues,
  ].filter(i => i.severity === 'critical' || i.severity === 'high');

  const getScoreColor = (score: number) => {
    if (score >= 80) return '#10B981';
    if (score >= 60) return '#F59E0B';
    return '#EF4444';
  };

  const getScoreLabel = (score: number) => {
    if (score >= 90) return 'Excellent';
    if (score >= 80) return 'Good';
    if (score >= 60) return 'Needs Improvement';
    return 'Poor';
  };

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Your Website Audit Report</title>
</head>
<body style="margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: #f3f4f6;">
  <table role="presentation" style="width: 100%; border-collapse: collapse;">
    <tr>
      <td style="padding: 40px 20px;">
        <table role="presentation" style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);">

          <!-- Header -->
          <tr>
            <td style="background: linear-gradient(135deg, #91CB5A 0%, #6BA839 100%); padding: 40px 30px; text-align: center;">
              <h1 style="margin: 0; color: #ffffff; font-size: 28px; font-weight: bold;">
                Website Audit Complete
              </h1>
              <p style="margin: 10px 0 0; color: #ffffff; opacity: 0.9; font-size: 14px;">
                Generated by ${companyName}
              </p>
            </td>
          </tr>

          <!-- Overall Score -->
          <tr>
            <td style="padding: 40px 30px; text-align: center; background-color: #f9fafb;">
              <h2 style="margin: 0 0 10px; color: #111827; font-size: 18px;">Overall Health Score</h2>
              <div style="display: inline-block; padding: 20px 40px; background-color: #ffffff; border-radius: 12px; box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);">
                <div style="font-size: 56px; font-weight: bold; color: ${getScoreColor(results.overallScore)}; line-height: 1;">
                  ${results.overallScore}
                </div>
                <div style="font-size: 14px; color: #6b7280; margin-top: 5px;">
                  ${getScoreLabel(results.overallScore)}
                </div>
              </div>
              <p style="margin: 20px 0 0; color: #6b7280; font-size: 14px;">
                <strong>${results.url}</strong>
              </p>
            </td>
          </tr>

          <!-- Category Scores -->
          <tr>
            <td style="padding: 0 30px 30px;">
              <h3 style="margin: 0 0 20px; color: #111827; font-size: 16px;">Category Breakdown</h3>
              ${[
                { name: 'SEO', score: results.seo.score, icon: '🔍' },
                { name: 'Performance', score: results.performance.score, icon: '⚡' },
                { name: 'Accessibility', score: results.accessibility.score, icon: '♿' },
                { name: 'Security', score: results.security.score, icon: '🔒' },
                { name: 'Shopify', score: results.shopify.score, icon: '🛍️' },
                { name: 'Sales Optimization', score: results.salesOptimization.score, icon: '💰' },
              ]
                .map(
                  (cat) => `
                <div style="margin-bottom: 15px;">
                  <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 5px;">
                    <span style="font-size: 14px; color: #374151;">
                      ${cat.icon} ${cat.name}
                    </span>
                    <span style="font-size: 16px; font-weight: bold; color: ${getScoreColor(cat.score)};">
                      ${cat.score}
                    </span>
                  </div>
                  <div style="background-color: #e5e7eb; height: 8px; border-radius: 4px; overflow: hidden;">
                    <div style="background-color: ${getScoreColor(cat.score)}; height: 100%; width: ${cat.score}%; transition: width 0.3s ease;"></div>
                  </div>
                </div>
              `
                )
                .join('')}
            </td>
          </tr>

          <!-- Critical Issues -->
          ${
            criticalIssues.length > 0
              ? `
          <tr>
            <td style="padding: 0 30px 30px;">
              <h3 style="margin: 0 0 15px; color: #111827; font-size: 16px;">
                ⚠️ Priority Issues (${criticalIssues.length})
              </h3>
              ${criticalIssues
                .slice(0, 5)
                .map(
                  (issue) => `
                <div style="margin-bottom: 12px; padding: 12px; background-color: ${
                  issue.severity === 'critical' ? '#FEF2F2' : '#FEF3C7'
                }; border-left: 4px solid ${issue.severity === 'critical' ? '#EF4444' : '#F59E0B'}; border-radius: 4px;">
                  <div style="font-weight: 600; color: #111827; font-size: 13px; margin-bottom: 4px;">
                    ${issue.issue}
                  </div>
                  <div style="color: #6b7280; font-size: 12px;">
                    ${issue.recommendation}
                  </div>
                </div>
              `
                )
                .join('')}
              ${
                criticalIssues.length > 5
                  ? `<p style="color: #6b7280; font-size: 12px; margin: 10px 0 0;">
                      And ${criticalIssues.length - 5} more issues...
                    </p>`
                  : ''
              }
            </td>
          </tr>
          `
              : `
          <tr>
            <td style="padding: 0 30px 30px;">
              <div style="padding: 20px; background-color: #ECFDF5; border-left: 4px solid #10B981; border-radius: 4px; text-align: center;">
                <div style="font-size: 24px; margin-bottom: 5px;">✓</div>
                <div style="color: #065F46; font-weight: 600;">No critical issues found!</div>
              </div>
            </td>
          </tr>
          `
          }

          <!-- CTA -->
          <tr>
            <td style="padding: 30px; background-color: #f9fafb; text-align: center;">
              <p style="margin: 0 0 20px; color: #374151; font-size: 14px;">
                View your complete audit report with detailed recommendations
              </p>
              <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://scalefront.io'}/earn"
                 style="display: inline-block; padding: 12px 32px; background-color: #91CB5A; color: #ffffff; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 14px;">
                View Full Report
              </a>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding: 30px; background-color: #111827; text-align: center;">
              <p style="margin: 0 0 10px; color: #9ca3af; font-size: 12px;">
                This audit was generated by ${companyName}
              </p>
              <p style="margin: 0; color: #6b7280; font-size: 12px;">
                ${new Date(results.timestamp).toLocaleString()}
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
  `;
}

export async function sendAuditResults(email: string, results: FullAuditResults, companyName?: string): Promise<boolean> {
  const url = new URL(results.url);
  const subject = `Audit Report for ${url.hostname} - Score: ${results.overallScore}/100`;
  const html = generateAuditEmail(results, companyName);

  return sendEmail({
    to: email,
    subject,
    html,
  });
}
